#############################################################################
# Makefile for building: proj2.app/Contents/MacOS/proj2
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  proj2.pro
# Template: app
# Command: /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake -o Makefile proj2.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.14.2/5.14.2/clang_64/lib/QtMultimedia.framework/Headers -I../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I../../Qt5.14.2/5.14.2/clang_64/lib/QtNetwork.framework/Headers -I../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib
QMAKE         = /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = proj21.0.0
DISTDIR = /Users/pro/Desktop/proj2/.tmp/proj21.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/pro/Qt5.14.2/5.14.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib -framework QtMultimedia -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = enermy.cpp \
		gamestart.cpp \
		main.cpp \
		mainwindow.cpp qrc_myResources.cpp \
		moc_gamestart.cpp \
		moc_mainwindow.cpp
OBJECTS       = enermy.o \
		gamestart.o \
		main.o \
		mainwindow.o \
		qrc_myResources.o \
		moc_gamestart.o \
		moc_mainwindow.o
DIST          = ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/lex.prf \
		proj2.pro enermy.h \
		gamestart.h \
		mainwindow.h enermy.cpp \
		gamestart.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = proj2
DESTDIR       = 
TARGET        = proj2.app/Contents/MacOS/proj2

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/pro/Desktop/proj2/proj2.pro


include /Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

proj2.app/Contents/MacOS/proj2: ui_gamestart.h ui_mainwindow.h $(OBJECTS)  
	@test -d proj2.app/Contents/MacOS/ || mkdir -p proj2.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: proj2.pro ../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/lex.prf \
		proj2.pro \
		myResources.qrc \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtMultimedia.framework/Resources/QtMultimedia.prl \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile proj2.pro -spec macx-clang CONFIG+=x86_64
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/qdevice.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/device_config.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/unix.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/mac.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/macx.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/qconfig.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_post.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/mac.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources_functions.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/moc.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/uic.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qmake_use.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/yacc.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/lex.prf:
proj2.pro:
myResources.qrc:
../../Qt5.14.2/5.14.2/clang_64/lib/QtMultimedia.framework/Resources/QtMultimedia.prl:
../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../Qt5.14.2/5.14.2/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile proj2.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

proj2.app/Contents/PkgInfo: 
	@test -d proj2.app/Contents || mkdir -p proj2.app/Contents
	@$(DEL_FILE) proj2.app/Contents/PkgInfo
	@echo "APPL????" > proj2.app/Contents/PkgInfo
proj2.app/Contents/Resources/empty.lproj: 
	@test -d proj2.app/Contents/Resources || mkdir -p proj2.app/Contents/Resources
	@touch proj2.app/Contents/Resources/empty.lproj
	
proj2.app/Contents/Info.plist: 
	@test -d proj2.app/Contents || mkdir -p proj2.app/Contents
	@$(DEL_FILE) proj2.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,guqiuhan.proj2,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},guqiuhan.proj2,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,proj2,g" -e "s,@LIBRARY@,proj2,g" -e "s,\$${EXECUTABLE_NAME},proj2,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/Info.plist.app >proj2.app/Contents/Info.plist

all: Makefile \
		proj2.app/Contents/PkgInfo \
		proj2.app/Contents/Resources/empty.lproj \
		proj2.app/Contents/Info.plist proj2.app/Contents/MacOS/proj2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents myResources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents enermy.h gamestart.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents enermy.cpp gamestart.cpp main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gamestart.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r proj2.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=x86_64

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_myResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_myResources.cpp
qrc_myResources.cpp: myResources.qrc \
		../../Qt5.14.2/5.14.2/clang_64/bin/rcc \
		map2.gif \
		bat.gif
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/rcc -name myResources myResources.qrc -o qrc_myResources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_gamestart.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gamestart.cpp moc_mainwindow.cpp
moc_gamestart.cpp: gamestart.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj2/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj2 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtMultimedia.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtNetwork.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib gamestart.h -o moc_gamestart.cpp

moc_mainwindow.cpp: mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj2/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj2 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtMultimedia.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtNetwork.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_gamestart.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_gamestart.h ui_mainwindow.h
ui_gamestart.h: gamestart.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic gamestart.ui -o ui_gamestart.h

ui_mainwindow.h: mainwindow.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

enermy.o: enermy.cpp enermy.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QMovie \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QList \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enermy.o enermy.cpp

gamestart.o: gamestart.cpp gamestart.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_gamestart.h \
		mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamestart.o gamestart.cpp

main.o: main.cpp ../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		gamestart.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		ui_mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QMovie \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		enermy.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_myResources.o: qrc_myResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_myResources.o qrc_myResources.cpp

moc_gamestart.o: moc_gamestart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamestart.o moc_gamestart.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/proj2/bin || mkdir -p $(INSTALL_ROOT)/opt/proj2/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/proj2/bin/proj2.app
	
	$(QINSTALL) proj2.app $(INSTALL_ROOT)/opt/proj2/bin/proj2.app
	-$(STRIP) $(INSTALL_ROOT)/opt/proj2/bin/proj2.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/proj2/bin/proj2.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/proj2/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

